### ISSUE TITLE
acronym.sty regression

### ISSUE THREAD

**Issue by bfirsh** [brucemiller/LaTeXML#1147]
[When upgrading LaTeXML](https://github.com/arxiv-vanity/engrafo/pull/770) I think I have found a regression somewhere between 4b0ff06a1f700b34550e95be1f2efe6a38bbc582.. 5da20f166eb22fdf6f2b9083071eddfcdd699645.

[This document](https://github.com/arxiv-vanity/engrafo/blob/3e0ed5a96138dce13a115a46e8cf7e4cec1e7617/tests/integration/packages/acronym.sty.tex) rendered fine using 4b0ff06a1f700b34550e95be1f2efe6a38bbc582 but now the acronyms don't seem to resolve. E.g.:

```html
<span title="" class="ltx_glossaryref ltx_missing">GSM</span>
```

**Comment by dginev** [comment]
Log:
```
Warning:malformed:ltx:glossaryphrase No open node can contain element 'ltx:glossaryphrase'
	at acrotest.tex; line 50 col 0 - line 64 col 13
	XMLDocument[94429500654080]<ltx:document _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." xmlns="http://dlmf.nist.gov/LaTeXML">...<ltx:section _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." inlist="toc" xml:id="S3" _ID_counter__="11" _ID_counter_m_="6">...<ltx:glossary _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." class="ltx_acronym" lists="acronym">...<ltx:glossarylist _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b...">...
	In Core::Document[@0x55e21499f9c8] /tmp/acrotest.tex; from line 50 col 0 to line 64 col 13

Error:malformed:ltx:glossaryphrase <ltx:glossaryphrase> isn't allowed in <ltx:glossarylist>
	at acrotest.tex; line 50 col 0 - line 64 col 13
	Currently in XMLDocument[94429500654080]<ltx:document _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." xmlns="http://dlmf.nist.gov/LaTeXML">...<ltx:section _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." inlist="toc" xml:id="S3" _ID_counter__="11" _ID_counter_m_="6">...<ltx:glossary _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." class="ltx_acronym" lists="acronym">...<ltx:glossarylist _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b...">...
	In Core::Document[@0x55e21499f9c8] /tmp/acrotest.tex; from line 50 col 0 to line 64 col 13
	 <= Core::Definition::Constructor[\lx@@ac... <= Whatsit[\lx@@acro@phrase,Core::List[B... <= Core::Document[@0x55e21499f9c8] <= ...

Warning:malformed:ltx:glossaryphrase No open node can contain element 'ltx:glossaryphrase'
	at acrotest.tex; line 50 col 0 - line 64 col 13
	XMLDocument[94429500654080]<ltx:document _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." xmlns="http://dlmf.nist.gov/LaTeXML">...<ltx:section _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." inlist="toc" xml:id="S3" _ID_counter__="11" _ID_counter_m_="6">...<ltx:glossary _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." class="ltx_acronym" lists="acronym">...<ltx:glossarylist _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b...">...
	In Core::Document[@0x55e21499f9c8] /tmp/acrotest.tex; from line 50 col 0 to line 64 col 13

Error:malformed:ltx:glossaryphrase <ltx:glossaryphrase> isn't allowed in <ltx:glossarylist>
	at acrotest.tex; line 50 col 0 - line 64 col 13
	Currently in XMLDocument[94429500654080]<ltx:document _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." xmlns="http://dlmf.nist.gov/LaTeXML">...<ltx:section _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." inlist="toc" xml:id="S3" _ID_counter__="11" _ID_counter_m_="6">...<ltx:glossary _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b..." class="ltx_acronym" lists="acronym">...<ltx:glossarylist _box="LaTeXML::Core::Whatsit=HASH(0x..." _font="Font[serif,medium,upright,10,b...">...
	In Core::Document[@0x55e21499f9c8] /tmp/acrotest.tex; from line 50 col 0 to line 64 col 13
	 <= Core::Definition::Constructor[\lx@@ac... <= Whatsit[\lx@@acro@phrase,Core::List[B... <= Core::Document[@0x55e21499f9c8] <= ...
 0.12 sec)
```

Looks related to the recent upgrades to the bibliographic schema?

**Comment by brucemiller** [comment]
Indeed; 976f9e1 should fix it.  Sorry, too many tendriles in that multi-list;multi-bib;multi-appendix patch!  Thanks for the quick catch!!

**Comment by dginev** [comment]
@brucemiller do you think we should grab the acronym tex file Ben is testing against and add it as a latexml test?

**Comment by brucemiller** [comment]
On 5/24/19 2:03 PM, Deyan Ginev wrote:
> @brucemiller <https://github.com/brucemiller> do you think we should 
> grab the acronym tex file Ben is testing against and add it as a latexml 
> test?

Sure; Done!

**Comment by bfirsh** [comment]
Bumped this again to master and still seeing a weird regression:

<img width="816" alt="Screenshot 2019-05-28 10 52 46" src="https://user-images.githubusercontent.com/40906/58469290-1bbbfd00-8137-11e9-9772-79f52dfa4ec7.png">

**Comment by brucemiller** [comment]
I'm having a bad day; Things just won't stay fixed!  But should be good now (again). Thanks for the report!

**Comment by bfirsh** [comment]
Thank you for the fix! :D
